const rawList =[

  { value: "MCX.NS", label: "MCX" },
  { value: "CREDITACC.NS", label: "CREDITACC" },
  { value: "DEEPAKNTR.NS", label: "DEEPAKNTR" },
  { value: "AMBER.NS", label: "AMBER" },
  { value: "SKFINDIA.NS", label: "SKFINDIA" },
  { value: "CMSINFO.NS", label: "CMSINFO" },
  { value: "BANKINDIA.NS", label: "BANKINDIA" },
  { value: "JYOTHYLAB.NS", label: "JYOTHYLAB" },
  { value: "ASIANHOTNR.NS", label: "ASIANHOTNR" },
  { value: "HITECH.NS", label: "HITECH" },
  { value: "ZEELEARN.NS", label: "ZEELEARN" },
  { value: "FINOPB.NS", label: "FINOPB" },
  { value: "BLUEJET.NS", label: "BLUEJET" },
  { value: "CAPITALSFB.NS", label: "CAPITALSFB" },
  { value: "JAYNECOIND.NS", label: "JAYNECOIND" },
  { value: "UNIENTER.NS", label: "UNIENTER" },
  { value: "UNIPARTS.NS", label: "UNIPARTS" },
  { value: "CHOLAHLDNG.NS", label: "CHOLAHLDNG" },
  { value: "ARVINDFASN.NS", label: "ARVINDFASN" },
  { value: "EMCURE.NS", label: "EMCURE" },
  { value: "SCHAEFFLER.NS", label: "SCHAEFFLER" },
  { value: "GUJGASLTD.NS", label: "GUJGASLTD" },
  { value: "EQUITASBNK.NS", label: "EQUITASBNK" },
  { value: "RAYMOND.NS", label: "RAYMOND" },
  { value: "LAURUSLABS.NS", label: "LAURUSLABS" },
  { value: "KAYNES.NS", label: "KAYNES" },
  { value: "MEDANTA.NS", label: "MEDANTA" },
  { value: "ARVIND.NS", label: "ARVIND" },
  { value: "JAYSREETEA.NS", label: "JAYSREETEA" },
  { value: "AJMERA.NS", label: "AJMERA" },
  { value: "GMBREW.NS", label: "GMBREW" },
  { value: "WINDLAS.NS", label: "WINDLAS" },
  { value: "NAHARCAP.NS", label: "NAHARCAP" },
  { value: "RESPONIND.NS", label: "RESPONIND" },
  { value: "VASCONEQ.NS", label: "VASCONEQ" },
  { value: "CENTUM.NS", label: "CENTUM" },
  { value: "JASH.NS", label: "JASH" },
  { value: "PVSL.NS", label: "PVSL" },
  { value: "FAIRCHEMOR.NS", label: "FAIRCHEMOR" },
  { value: "INDORAMA.NS", label: "INDORAMA" },
];

const stocklist = Array.from(new Map(rawList.map(s => [s.value, s])).values());

export default stocklist;
